### ISSUE TITLE
Compability problem with foreman 1.17?

### ISSUE THREAD

**Issue by selund** [ananace/foreman_wds#1]
I tried to use this plugin with foreman 1.17, however it doesn't work, I'm not sure if it's a compability problem? Or me doing something stupid.... ?

From the log I see the following.

2018-06-04T11:44:43 4ea196dc [app] [I] Started GET "/javascripts/locale/en/app.js" for <clien> at 2018-06-04 11:44:43 +0200
2018-06-04T11:44:43 051b26a3 [app] [I] Started GET "/javascripts/foreman_wds/wds_servers.js" for <clien> at 2018-06-04 11:44:43 +0200
2018-06-04T11:44:43 4ea196dc [app] [F]   
2018-06-04T11:44:43 4ea196dc [app] [F] ActionController::RoutingError (No route matches [GET] "/javascripts/locale/en/app.js"):
2018-06-04T11:44:43 4ea196dc [app] [F]   
2018-06-04T11:44:43 4ea196dc [app] [F] lib/middleware/tagged_logging.rb:18:in `call'
2018-06-04T11:44:43 051b26a3 [app] [F]   
2018-06-04T11:44:43 051b26a3 [app] [F] ActionController::RoutingError (No route matches [GET] "/javascripts/foreman_wds/wds_servers.js"):
2018-06-04T11:44:43 051b26a3 [app] [F]   
2018-06-04T11:44:43 051b26a3 [app] [F] lib/middleware/tagged_logging.rb:18:in `call'
2018-06-04T11:44:43 67eafaf1 [app] [I] Started GET "/javascripts/locale/en/app.js" for <clien> at 2018-06-04 11:44:43 +0200
2018-06-04T11:44:43 67eafaf1 [app] [F]   
2018-06-04T11:44:43 67eafaf1 [app] [F] ActionController::RoutingError (No route matches [GET] "/javascripts/locale/en/app.js"):
2018-06-04T11:44:43 67eafaf1 [app] [F]   
2018-06-04T11:44:43 67eafaf1 [app] [F] lib/middleware/tagged_logging.rb:18:in `call'
2018-06-04T11:44:43 f9c907f9 [app] [I] Started GET "/javascripts/foreman_wds/wds_servers.js" for <clien> at 2018-06-04 11:44:43 +0200
2018-06-04T11:44:43 f9c907f9 [app] [F]   
2018-06-04T11:44:43 f9c907f9 [app] [F] ActionController::RoutingError (No route matches [GET] "/javascripts/foreman_wds/wds_servers.js"):
2018-06-04T11:44:43 f9c907f9 [app] [F]   
2018-06-04T11:44:43 f9c907f9 [app] [F] lib/middleware/tagged_logging.rb:18:in `call'
2018-06-04T11:44:43 b92e0396 [app] [I] Started GET "/notification_recipients" for <clien> at 2018-06-04 11:44:43 +0200

**Comment by ananace** [comment]
That should just mean that it wasn't able to discover a path for
downloading the JavaScript files, which probably isn't a compatibility
issue.

I might have to look over the asset paths though, might be a mistake there
or in the precompile.

**Comment by ananace** [comment]
Could you run `rake plugin:assets:precompile[foreman_wds]` (foreman-rake if you're on CentOS) in your Foreman?

**Comment by selund** [comment]
I'ts a Debian server, so foreman-rake here as well...

# foreman-rake plugin:assets:precompile[foreman_wds] --trace
** Invoke plugin:assets:precompile (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute plugin:assets:precompile
rake aborted!
NameError: uninitialized constant Foreman::PluginAssetsTask::Sass
/usr/share/foreman/vendor/ruby/2.3.0/gems/foreman_hooks-0.3.14/lib/foreman_hooks/as_dependencies_hook.rb:4:in `load_missing_constant'
/usr/share/foreman/lib/tasks/plugin_assets.rake:54:in `initialize'
/usr/share/foreman/lib/tasks/plugin_assets.rake:121:in `new'
/usr/share/foreman/lib/tasks/plugin_assets.rake:121:in `block in <top (required)>'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/usr/bin/rake:27:in `<main>'
Tasks: TOP => plugin:assets:precompile

**Comment by ananace** [comment]
Right, yes. You probably need the `foreman-assets` package installed to be able to do the precompile.

And I guess the foreman-rake helper exists for all packaged versions.

**Comment by selund** [comment]
That helped allot :) I'll report back if I find any more problems.

**Comment by ananace** [comment]
Great, I'll close this issue then and add information about the asset precompilation into the readme.

Thanks for trying it out and reporting issues. :1st_place_medal:
